# Generated by Django 5.2 on 2025-04-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0003_student_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaher_name', models.CharField(max_length=100)),
            ],
        ),
    ]
