# Generated by Django 5.2 on 2025-04-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0004_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teaher_name',
            new_name='teacher_name',
        ),
    ]
