# Generated by Django 5.2 on 2025-05-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0005_rename_teaher_name_teacher_teacher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(to='student_records.course'),
        ),
    ]
