# Generated by Django 5.2 on 2025-06-11 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_records', '0007_remove_student_email_student_roll_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_records.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_records.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_records.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_records.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_records.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_records.teacher')),
            ],
        ),
    ]
